language: python

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
      dist: xenial

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
   py.test --cov=coupled_biased_random_walks/

after_success:
  - coveralls
